"""논지 유니크 제약을 활성 건에만 적용

Revision ID: 207f00d842f2
Revises: c064732c4541
Create Date: 2026-08-19 14:21:15.425181
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401  (autogenerate가 VECTOR 타입을 참조한다)


revision = '207f00d842f2'
down_revision = 'c064732c4541'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_thesis_user_ticker_active'), 'wiki_theses', type_='unique')
    op.create_index('uq_thesis_active_per_ticker', 'wiki_theses', ['user_id', 'ticker'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_thesis_active_per_ticker', table_name='wiki_theses', postgresql_where=sa.text("status = 'active'"))
    op.create_unique_constraint(op.f('uq_thesis_user_ticker_active'), 'wiki_theses', ['user_id', 'ticker', 'status'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
