"""초기 스키마

Revision ID: c064732c4541
Revises: 
Create Date: 2026-08-19 11:59:41.004002
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = 'c064732c4541'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_responses',
    sa.Column('request_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('endpoint', sa.String(length=60), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=40), nullable=True),
    sa.Column('effort', sa.String(length=10), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('guardrail_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index('ix_ai_responses_created', 'ai_responses', ['created_at'], unique=False)
    op.create_table('index_daily',
    sa.Column('index_code', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('index_code', 'trade_date')
    )
    op.create_table('instruments',
    sa.Column('ticker', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('sector', sa.String(length=60), nullable=True),
    sa.Column('sector_code', sa.String(length=20), nullable=True),
    sa.Column('corp_code', sa.String(length=8), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('listed_shares', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(ticker) = 6', name='ck_instruments_ticker_len'),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index('ix_instruments_corp_code', 'instruments', ['corp_code'], unique=False)
    op.create_index('ix_instruments_sector', 'instruments', ['sector'], unique=False)
    op.create_table('trade_watermarks',
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('last_trade_id', sa.String(length=40), nullable=True),
    sa.Column('polled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('wiki_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('editable', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wiki_facts_user', 'wiki_facts', ['user_id', 'deleted_at'], unique=False)
    op.create_table('wiki_theses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('ticker', sa.String(length=6), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('horizon', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('linked_trade_id', sa.String(length=40), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', 'status', name='uq_thesis_user_ticker_active')
    )
    op.create_index('ix_wiki_theses_user', 'wiki_theses', ['user_id'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('rating', sa.String(length=6), nullable=False),
    sa.Column('reasons', sa.ARRAY(sa.String(length=24)), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['ai_responses.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('ticker', sa.String(length=6), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['instruments.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_documents_source_external')
    )
    op.create_index('ix_documents_ticker_published', 'documents', ['ticker', 'published_at'], unique=False)
    op.create_table('price_daily',
    sa.Column('ticker', sa.String(length=6), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Integer(), nullable=True),
    sa.Column('high', sa.Integer(), nullable=True),
    sa.Column('low', sa.Integer(), nullable=True),
    sa.Column('close', sa.Integer(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('trade_value', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['instruments.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticker', 'trade_date')
    )
    op.create_index('ix_price_daily_date', 'price_daily', ['trade_date'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunk_doc_index')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('ticker', sa.String(length=6), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticker'], ['instruments.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_date_ticker', 'events', ['event_date', 'ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_date_ticker', table_name='events')
    op.drop_table('events')
    op.drop_table('document_chunks')
    op.drop_index('ix_price_daily_date', table_name='price_daily')
    op.drop_table('price_daily')
    op.drop_index('ix_documents_ticker_published', table_name='documents')
    op.drop_table('documents')
    op.drop_table('ai_feedback')
    op.drop_index('ix_wiki_theses_user', table_name='wiki_theses')
    op.drop_table('wiki_theses')
    op.drop_index('ix_wiki_facts_user', table_name='wiki_facts')
    op.drop_table('wiki_facts')
    op.drop_table('trade_watermarks')
    op.drop_index('ix_instruments_sector', table_name='instruments')
    op.drop_index('ix_instruments_corp_code', table_name='instruments')
    op.drop_table('instruments')
    op.drop_table('index_daily')
    op.drop_index('ix_ai_responses_created', table_name='ai_responses')
    op.drop_table('ai_responses')
    # ### end Alembic commands ###
