"""재무 연간 테이블 — 자본총계

Revision ID: ee8e10ddd35b
Revises: 207f00d842f2
Create Date: 2026-08-19 19:43:30.875062
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401  (autogenerate가 VECTOR 타입을 참조한다)


revision = 'ee8e10ddd35b'
down_revision = '207f00d842f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_annual',
    sa.Column('ticker', sa.String(length=6), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('total_equity', sa.BigInteger(), nullable=False),
    sa.Column('fs_div', sa.String(length=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fs_div IN ('CFS', 'OFS')", name='ck_financial_annual_fs_div'),
    sa.ForeignKeyConstraint(['ticker'], ['instruments.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticker', 'fiscal_year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_annual')
    # ### end Alembic commands ###
